version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"  # Evita conflicto si algo usa 5000 en el host
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - MYSQL_HOST=flask_db  # Este debe coincidir con el nombre del contenedor de MySQL
      - MYSQL_USER=vetting
      - MYSQL_PASSWORD=vehrso
      - MYSQL_DATABASE=vetting
    networks:
      - flasknet

  db:
    image: mysql:8.0
    container_name: flask_db  # Cambiado para que no colisione con "mysql_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vehrso
      MYSQL_DATABASE: vetting
    ports:
      - "3309:3306"  # Evita conflicto con el 3308 ya usado por el primer MySQL
    volumes:
      - flask_mysql_data:/var/lib/mysql
    networks:
      - flasknet

volumes:
  flask_mysql_data:

networks:
  flasknet:
